package com.example.subscription_platform.dto.analytics;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Response DTO for plan popularity analytics.
 * Shows how popular each subscription plan is based on subscriber count and
 * revenue.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PlanPopularityResponse {

    /**
     * Unique identifier of the plan.
     */
    private String planId;

    /**
     * Name of the subscription plan.
     */
    private String planName;

    /**
     * Price of the plan.
     */
    private BigDecimal planPrice;

    /**
     * Number of currently active subscribers on this plan.
     */
    private Long activeSubscribers;

    /**
     * Total number of subscriptions (all time) for this plan.
     */
    private Long totalSubscriptions;

    /**
     * Total revenue generated by this plan.
     */
    private BigDecimal totalRevenue;

    /**
     * Percentage of total active subscriptions this plan represents.
     */
    private Double percentageOfTotal;

    /**
     * Ranking position (1 = most popular).
     */
    private Integer rank;
}
